spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/websocket_chat_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: devit
    password: 새비밀번호 # 비밀번호가 정확한지 다시 한번 확인하세요.
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA (Hibernate) 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Spring Security 및 OAuth 2.0 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 877657680277-mhmphpq00ldjm3jnqm8mc3ncocj4ioth.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile